### ISSUE TITLE
Better login method.

### ISSUE THREAD

**Issue by indrakaw** [RX14/discord-curses#17]
Is there another way to login without input password into cli? e.g. `npm start my@email.com -p` then input password; password is hidden and can't be read in cli history.

**Comment by indrakaw** [comment]
ping @RX14.

**Comment by RX14** [comment]
Duplicate of #4

**Comment by RX14** [comment]
No, it's not yet possible, and pinging me doesn't help when i'm not there.

I get pinged by the issue being opened, you don't need to mention me.
